In [3]:
import pandas as pd
import numpy as np

In [20]:
S1player2019 = pd.read_csv("C:/Users/William Wu/Documents/Overwatch League Stats/Raw Data/phs_2019_stage_1.csv")
S2player2019 = pd.read_csv("C:/Users/William Wu/Documents/Overwatch League Stats/Raw Data/phs_2019_stage_2.csv")
S3player2019 = pd.read_csv("C:/Users/William Wu/Documents/Overwatch League Stats/Raw Data/phs_2019_stage_3.csv")
S4player2019 = pd.read_csv("C:/Users/William Wu/Documents/Overwatch League Stats/Raw Data/phs_2019_stage_4.csv")
SPplayer2019 = pd.read_csv("C:/Users/William Wu/Documents/Overwatch League Stats/Raw Data/phs_2019_playoffs.csv")

In [16]:
S1player2019.head()

,pelstart_time,match_id,stage,map_type,map_name,player,team,stat_name,hero,stat_amount
0,2/15/2019 0:11,21211,Overwatch League Stage 1,CONTROL,Ilios,Bdosin,London Spitfire,All Damage Done,All Heroes,14845.193400
1,2/15/2019 0:11,21211,Overwatch League Stage 1,CONTROL,Ilios,Bdosin,London Spitfire,Assists,All Heroes,13.000000
2,2/15/2019 0:11,21211,Overwatch League Stage 1,CONTROL,Ilios,Bdosin,London Spitfire,Average Time Alive,All Heroes,87.623574
3,2/15/2019 0:11,21211,Overwatch League Stage 1,CONTROL,Ilios,Bdosin,London Spitfire,Barrier Damage Done,All Heroes,5674.344475
4,2/15/2019 0:11,21211,Overwatch League Stage 1,CONTROL,Ilios,Bdosin,London Spitfire,Damage - Quick Melee,All Heroes,78.000000

In [24]:
S1player2019["stage"] = "Stage 1"
S2player2019["stage"] = "Stage 2"
S3player2019["stage"] = "Stage 3"
S4player2019["stage"] = "Stage 4"
SPplayer2019["stage"] = "Playoffs"
SPplayer2019.head()

,start_time,match_id,stage,map_type,map_name,player,team,stat_name,hero,stat_amount
0,8/31/2019 1:09,30172,Playoffs,CONTROL,Ilios,Elsa,Chengdu Hunters,All Damage Done,All Heroes,19059.670270
1,8/31/2019 1:09,30172,Playoffs,CONTROL,Ilios,Elsa,Chengdu Hunters,Assists,All Heroes,22.000000
2,8/31/2019 1:09,30172,Playoffs,CONTROL,Ilios,Elsa,Chengdu Hunters,Average Time Alive,All Heroes,302.704223
3,8/31/2019 1:09,30172,Playoffs,CONTROL,Ilios,Elsa,Chengdu Hunters,Barrier Damage Done,All Heroes,8861.540116
4,8/31/2019 1:09,30172,Playoffs,CONTROL,Ilios,Elsa,Chengdu Hunters,Damage - Quick Melee,All Heroes,152.999995

In [25]:
player2019 = S1player2019.append(S2player2019, ignore_index = True).append(S3player2019, ignore_index = True).append(S4player2019, ignore_index = True).append(SPplayer2019, ignore_index = True)
player2019.head()

,hero,map_name,map_type,match_id,pelstart_time,player,stage,start_time,stat_amount,stat_name,team
0,All Heroes,Ilios,CONTROL,21211,2/15/2019 0:11,Bdosin,Stage 1,NaN,14845.193400,All Damage Done,London Spitfire
1,All Heroes,Ilios,CONTROL,21211,2/15/2019 0:11,Bdosin,Stage 1,NaN,13.000000,Assists,London Spitfire
2,All Heroes,Ilios,CONTROL,21211,2/15/2019 0:11,Bdosin,Stage 1,NaN,87.623574,Average Time Alive,London Spitfire
3,All Heroes,Ilios,CONTROL,21211,2/15/2019 0:11,Bdosin,Stage 1,NaN,5674.344475,Barrier Damage Done,London Spitfire
4,All Heroes,Ilios,CONTROL,21211,2/15/2019 0:11,Bdosin,Stage 1,NaN,78.000000,Damage - Quick Melee,London Spitfire

In [26]:
herotime = player2019.loc[player2019["stat_name"] == "Time Played"]
herotime = herotime.loc[player2019["hero"] != "All Heroes"]
herotime.head()

,hero,map_name,map_type,match_id,pelstart_time,player,stage,start_time,stat_amount,stat_name,team
66,Zenyatta,Ilios,CONTROL,21211,2/15/2019 0:11,Bdosin,Stage 1,NaN,655.895890,Time Played,London Spitfire
120,McCree,Ilios,CONTROL,21211,2/15/2019 0:11,Birdring,Stage 1,NaN,67.162571,Time Played,London Spitfire
162,Zarya,Ilios,CONTROL,21211,2/15/2019 0:11,Birdring,Stage 1,NaN,588.733318,Time Played,London Spitfire
234,D.Va,Ilios,CONTROL,21211,2/15/2019 0:11,Fury,Stage 1,NaN,650.057055,Time Played,London Spitfire
247,Wrecking Ball,Ilios,CONTROL,21211,2/15/2019 0:11,Fury,Stage 1,NaN,5.838835,Time Played,London Spitfire

In [30]:
heroesonly = herotime[["map_name","hero","stage","stat_amount"]]
heroesonly = heroesonly.rename(columns={'stat_amount': 'Time Played'})
heroesonly = heroesonly.groupby(["stage","map_name","hero"]).agg("sum")
heroesonly

                                             Time Played
stage    map_name            hero
Playoffs Busan               Ana              732.864804
                             Baptiste         746.568131
                             Bastion          356.271815
                             Doomfist       18527.858900
                             Lúcio          17836.812785
                             McCree           721.129019
                             Mei              647.183295
                             Mercy           1195.129706
                             Moira          18701.123722
                             Orisa          19063.083923
                             Pharah           302.679185
                             Reaper         17254.797167
                             Reinhardt         25.303261
                             Roadhog            0.971857
                             Sigma          19451.482985
                             Sombra           244.299827
                             Symmetra         524.672547
                             Tracer           118.748716
                             Widowmaker       514.858678
                             Wrecking Ball    671.657122
         Dorado              Ana             4419.985906
                             Baptiste        1999.494121
                             Bastion         1960.562833
                             D.Va             389.310781
                             Doomfist        5065.177663
                             Genji              4.868594
                             Hanzo             86.592529
                             Lúcio           4090.080433
                             McCree          2117.959007
                             Mei             2098.842754
...                                                  ...
Stage 4  Temple of Anubis    Zenyatta        5740.794449
         Volskaya Industries Ana            17522.029673
                             Ashe               5.843136
                             Baptiste       20520.518062
                             Bastion           28.221651
                             Brigitte          45.760149
                             D.Va            9947.431853
                             Doomfist         844.827604
                             Genji            922.830778
                             Hanzo          17585.000355
                             Lúcio           4554.223579
                             McCree          1073.606004
                             Mei            23662.457876
                             Mercy           8219.747584
                             Moira           1551.500574
                             Orisa          31121.109357
                             Pharah          2834.422509
                             Reaper          3214.870285
                             Reinhardt         88.604493
                             Roadhog        22301.717786
                             Soldier: 76       22.380485
                             Sombra           863.443210
                             Symmetra          89.535008
                             Torbjörn           3.893092
                             Tracer          1502.806362
                             Widowmaker     12609.294576
                             Winston          173.238269
                             Wrecking Ball   1516.471946
                             Zarya            114.859226
                             Zenyatta       12849.653308

[1617 rows x 1 columns]

In [33]:
heroesonly["Most Played"] = heroesonly.groupby(["stage","map_name"])["Time Played"].rank("dense", ascending = False)
heroesonly = heroesonly.sort_values(["stage","map_name", "Most Played"],ascending = True)
#heroesonly = heroesonly.loc[heroesonly["Most Played"]<= 6]
heroesonly

                                             Time Played  Most Played
stage    map_name            hero
Playoffs Busan               Sigma          19451.482985          1.0
                             Orisa          19063.083923          2.0
                             Moira          18701.123722          3.0
                             Doomfist       18527.858900          4.0
                             Lúcio          17836.812785          5.0
                             Reaper         17254.797167          6.0
                             Mercy           1195.129706          7.0
                             Baptiste         746.568131          8.0
                             Ana              732.864804          9.0
                             McCree           721.129019         10.0
                             Wrecking Ball    671.657122         11.0
                             Mei              647.183295         12.0
                             Symmetra         524.672547         13.0
                             Widowmaker       514.858678         14.0
                             Bastion          356.271815         15.0
                             Pharah           302.679185         16.0
                             Sombra           244.299827         17.0
                             Tracer           118.748716         18.0
                             Reinhardt         25.303261         19.0
                             Roadhog            0.971857         20.0
         Dorado              Sigma           9424.218144          1.0
                             Orisa           9001.764711          2.0
                             Doomfist        5065.177663          3.0
                             Mercy           4896.914068          4.0
                             Pharah          4657.512126          5.0
                             Moira           4423.009116          6.0
                             Ana             4419.985906          7.0
                             Lúcio           4090.080433          8.0
                             Reaper          3820.453279          9.0
                             McCree          2117.959007         10.0
...                                                  ...          ...
Stage 4  Temple of Anubis    Symmetra           1.945197         28.0
         Volskaya Industries Orisa          31121.109357          1.0
                             Mei            23662.457876          2.0
                             Roadhog        22301.717786          3.0
                             Baptiste       20520.518062          4.0
                             Hanzo          17585.000355          5.0
                             Ana            17522.029673          6.0
                             Zenyatta       12849.653308          7.0
                             Widowmaker     12609.294576          8.0
                             D.Va            9947.431853          9.0
                             Mercy           8219.747584         10.0
                             Lúcio           4554.223579         11.0
                             Reaper          3214.870285         12.0
                             Pharah          2834.422509         13.0
                             Moira           1551.500574         14.0
                             Wrecking Ball   1516.471946         15.0
                             Tracer          1502.806362         16.0
                             McCree          1073.606004         17.0
                             Genji            922.830778         18.0
                             Sombra           863.443210         19.0
                             Doomfist         844.827604         20.0
                             Winston          173.238269         21.0
                             Zarya            114.859226         22.0
                             Symmetra          89.535008         23.0
                             Reinhardt         88.604493         24.0
                             Brigitte          45.760149         25.0
                             Bastion           28.221651         26.0
                             Soldier: 76       22.380485         27.0
                             Ashe               5.843136         28.0
                             Torbjörn           3.893092         29.0

[1617 rows x 2 columns]

In [35]:
heroesonly.to_csv("2019playtime.csv")